function exceptionEmailList() {
  return [
"supervision777@gmail.com",
"beltreramon08@gmail.com",
"hanstaverasrd@gmail.com",
"vlad.jimnz2589@gmail.com",
"g.felizsoto@gmail.com",
"geronimoenglish@gmail.com",
"aditorres444@hotmail.com",
"fredespinal@yahoo.com ",
"tejeda_francisco@hotmail.com",
"elderalfredootanez@gmail.com",
"franciscoroot1@gmail.com",
"adonisfferreira@outlook.com",
"carlos63791@gmail.com",
"ldelacruz@uce.edu.do",
"omarhenriquez.work@gmail.com",
"borismarte.w@gmail.com",
"frankmrp21@gmail.com",
"caminoestrecho79@gmail.com",
"welin1992@gmail.com",
"lapiedra202@gmail.com",
"ing.fehidalgo@gmail.com",
"franziskabeckmann12@gmail.com ",
"bradleya.harmon@gmail.com",
"jesusmartinezc94@gmail.com",
"viktormichel@hotmail.com",
"mannylb01@gmail.com",
"deybimejia11@gmail.com",
"HANSTAVERASRD@GMAIL.COM",
"mveloz@ucateci.edu.do ",
"coordinatorpepin@gmail.com",
"fajardo500@gmail.com",
"immersionroberto@gmail.com",
"ppzd01@gmail.com",
"agrim.freddy.suero@gmail.com",
"victor.tejada12@gmail.com",
"deborah.larrauri@gmail.com ",
"rafaelreyespinales@hotmail.com",
"sabrina.benzant1@gmail.com",
"tmota@uce.edu.do",
"leoric.matos@gmail.com",
"cinthia-jh05@hotmail.com",
"castillo.amin001@gmail.com",
"joseluis1095@hotmail.com ",
"jpenglish2012@gmail.com",
"ralphxx@gmail.com",
"leidyea@gmail.com",
"pishes@gmail.com",
"cruz.medina2714@gmail.com",
"alwinnunez@gmail.com",
"sinnyinfante@yahoo.com",
"adams.claudio@gmail.com",
"elained.guzman@gmail.com",
"noelenglish@hotmail.com",
"jcp0594@gmail.com",
"ricardofm28@hotmail.com",
"jrgmz14@gmail.com",
"elained.guzman@gmail.com",
"anthony.ortega0902@gmail.com",
"bfsa2101@gmail.com",
"mishellesalcedodrv@gmail.com",
"alodisss@gmail.com",
"waldo23792@gmail.com",
]
}
